// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

uint16_t count = 0;
uint16_t preCount = 0;
char buffer[10];

void funcClick(lv_event_t * e)
{
	// Your code here
	lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED)
    {
		count = count + 1;
		lv_label_set_text_fmt(ui_lblCount, "Click: %d", count);
    }
}


/* Counter button event handler */
//   static void counter_event_handler(lv_event_t * e)
//   {
//     lv_event_code_t code = lv_event_get_code(e);
//     lv_obj_t *btn = lv_event_get_target(e);
//     if (code == LV_EVENT_CLICKED)
//     {
//       static uint8_t cnt = 0;
//       cnt++;
// 
//       /*Get the first child of the button which is the label and change its text*/
//       lv_obj_t *label = lv_obj_get_child(btn, 0);
//       lv_label_set_text_fmt(label, "Button: %d", cnt);
//       LV_LOG_USER("Clicked");
//       Serial.println("Clicked");
//     }
//   }


